version: '3.4'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
        - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo1
    networks:
      - samplenet

  mongo1:
    container_name: mongo_primary
    image: ${DOCKER_REGISTRY-}mongo:4.0.4
    ports:
      - "27017:27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs1", "--configsvr", "--port", "27017", "--bind_ip_all" ]
    networks:
      samplenet:
        aliases:
          - "mongo-primary"

  mongo2:
    container_name: mongo_secondary_1
    image: ${DOCKER_REGISTRY-}mongo:4.0.4
    ports:
      - "27018:27017"
    entrypoint: [ "/usr/bin/mongos", "--configdb", "rs1/mongo-primary:27017", "--port", "27017", "--bind_ip_all" ]
    networks:
      samplenet:
        aliases:
          - "mongo-secondary-1"

  mongo3:
    container_name: mongo_secondary_2
    image: ${DOCKER_REGISTRY-}mongo:4.0.4
    ports:
      - "27019:27017"
    entrypoint: [ "/usr/bin/mongod", "--shardsvr", "--replSet", "rs2", "--port", "27017", "--bind_ip_all" ]
    networks:
      samplenet:
        aliases:
          - "mongo-secondary-2"

  mongo4:
    container_name: mongo_secondary_3
    image: ${DOCKER_REGISTRY-}mongo:4.0.4
    ports:
      - "27020:27017"
    entrypoint: [ "/usr/bin/mongod", "--shardsvr", "--replSet", "rs3", "--port", "27017", "--bind_ip_all" ]
    networks:
      samplenet:
        aliases:
          - "mongo-secondary-3"

  mongo5:
    container_name: mongo_secondary_4
    image: ${DOCKER_REGISTRY-}mongo:4.0.4
    ports:
      - "27021:27017"
    entrypoint: [ "/usr/bin/mongod", "--shardsvr", "--replSet", "rs4", "--port", "27017", "--bind_ip_all" ]
    networks:
      samplenet:
        aliases:
          - "mongo-secondary-4"

  mongosetup:
    image: ${DOCKER_REGISTRY-}mongo:4.0.4
    volumes:
      - ./scripts:/scripts
    restart: always
    entrypoint: [ "bash", "/scripts/mongosetup.sh" ]
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - mongo4
      - mongo5
    networks:
      samplenet:
        aliases:
          - "mongo-aux"

networks:
  samplenet:
    driver: bridge
